#config_version=5

# Noah's test file for driving Andy Cavatorta's: Individual, Money, and Society

hardware:
    platform: p3_roc
    driverboards: pdb

switches:
    s_left_flipper:
        number: A0-B0-0
        tags: left_flipper
    s_left_launch:         
        number: A0-B0-1
    s_game_launch:         
        number: A0-B0-2
    s_right_launch:        
        number: A0-B0-3
    s_right_flipper:
        number: A0-B0-4
        tags: right_flipper

    s_pop_bumper_1:        
        number: A0-B1-0
    s_pop_bumper_2:        
        number: A0-B1-1
    s_pop_bumper_3:        
        number: A0-B1-2
    s_left_slingshot_main:        
        number: A0-B1-5
    s_right_slingshot_main:       
        number: A0-B1-4

coils:
    # Flippers
    c_flipper_left_main:
        number: A0-B1-0
        default_pulse_ms: 25
        default_pulse_power: 1.0
        allow_enable: true
    c_flipper_left_hold:
        number: A0-B1-1
        default_hold_power: 1.0
        allow_enable: true
        
    c_flipper_right_main:
        number: A0-B1-2
        default_pulse_ms: 15
        default_pulse_power: 1.0
        allow_enable: true
    c_flipper_right_hold:
        default_hold_power: 1.0
        number: A0-B1-3
        allow_enable: true


    # Slingshots
    c_slingshot_left_main:
        number: A0-B1-4
        default_pulse_ms: 10
    c_slingshot_right_main:
        number: A0-B1-5
        default_pulse_ms: 10
    

    # Pop Bumpers
    c_pop_bumper_1:
        number: A0-B0-2
        default_pulse_ms: 50
        default_pulse_power: 1.0
    c_pop_bumper_2:
        number: A0-B0-3
        default_pulse_ms: 50
        default_pulse_power: 1.0
    c_pop_bumper_3:
        default_pulse_ms: 50
        default_pulse_power: 1.0
        number: A0-B0-4

    # Launchers
    c_left_launch:
        number: A0-B0-1
        default_pulse_ms: 25
        default_pulse_power: 1.0
        
    c_right_launch:
        number: A0-B0-6
        default_pulse_ms: 25
        default_pulse_power: 1.0
        
    c_game_launch:
        number: A0-B0-0
        default_pulse_ms: 25
        default_pulse_power: 1.0
        
                
playfields:
    playfield:
        tags: default
        default_source_device: None  # use None in steps before 8
        #default_source_device: bd_trough  # use None in steps before 8

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
        enable_events: machine_reset_phase_3

autofire_coils:
    left_slingshot:
        coil: c_slingshot_right_main
        switch: s_left_slingshot_main
        enable_events: machine_reset_phase_3
    right_slingshot:
        coil: c_slingshot_left_main
        switch: s_right_slingshot_main
        enable_events: machine_reset_phase_3

    pop_bumper_1:
        coil: c_pop_bumper_1
        switch: s_pop_bumper_1
        enable_events: machine_reset_phase_3
    pop_bumper_2:
        coil: c_pop_bumper_2
        switch: s_pop_bumper_2
        enable_events: machine_reset_phase_3
    pop_bumper_3:
        coil: c_pop_bumper_3
        switch: s_pop_bumper_3
        enable_events: machine_reset_phase_3

    left_launch:
        coil: c_left_launch
        switch: s_left_launch
        enable_events: machine_reset_phase_3
        
    right_launch:
        coil: c_right_launch
        switch: s_right_launch
        enable_events: machine_reset_phase_3        
        
    game_launch:
        coil: c_game_launch
        switch: s_game_launch
        enable_events: machine_reset_phase_3



keyboard:
    z: 
        switch: s_left_flipper
    '/':
        switch: s_right_flipper
    a:
        switch: s_left_slingshot
    ';':
        switch: s_right_slingshot
    's':
        switch: s_start
    'q':
        switch: s_right_inlane
        
        
displays:
    window:
        width: 800
        height: 600


slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        font_size: 90
        color: yellow

      - type: rectangle
        width: 600
        height: 120
        color: green
        
#slide_player:
#  init_done: welcome_slide
##! test
#advance_time_and_run .1
        
modes:
  - base
  



