#config_version=5

# Noah's test file for driving Andy Cavatorta's: Individual, Money, and Society

hardware:
    platform: p3_roc
    driverboards: pdb

switches:
    s_start:
        number: A0-B0-5
        tags: start

    s_right_inlane:
        number: A0-B0-6
        tags: playfield_active

    s_trough1:
        number: A0-B1-7
        

    s_left_flipper:
        number: A0-B0-1
        tags: left_flipper
    s_right_flipper:
        number: A0-B0-3
        tags: right_flipper

    s_left_slingshot:
        number: A0-B0-0
        tags: left_flipper
    s_right_slingshot:
        number: A0-B0-2
        tags: right_flipper

    s_drop_target:
        number: A0-B0-4

coils:
    # Flippers
    c_flipper_left_main:
        number: A0-B0-6
        default_pulse_ms: 5
        default_pulse_power: 1.0
    c_flipper_left_hold:
        number: A0-B0-4
        default_hold_power: 1.0
        allow_enable: true
        
    c_flipper_right_main:
        number: A0-B0-7
        default_pulse_ms: 5
        default_pulse_power: 1.0
    c_flipper_right_hold:
        default_hold_power: 1.0
        number: A0-B0-5
        allow_enable: true

    c_trough_eject:
        number: A0-B0-0

    # Slingshots
    c_slingshot_left_main:
        number: A0-B0-2
        default_pulse_ms: 5
    c_slingshot_right_main:
        number: A0-B0-3
        default_pulse_ms: 5
    
    # Drop Targets
    c_reset_drop_target:
        number: A0-B0-1
        default_pulse_ms: 15
        default_pulse_power: 1.0
    c_knock_down_coil:
        number: A0-B1-7


playfields:
    playfield:
        default_source_device: bd_trough  # use None in steps before 8
        tags: default

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
        enable_events: machine_reset_phase_3

autofire_coils:
    left_slingshot:
        coil: c_slingshot_right_main
        switch: s_left_slingshot
        enable_events: machine_reset_phase_3
    right_slingshot:
        coil: c_slingshot_left_main
        switch: s_right_slingshot
        enable_events: machine_reset_phase_3

drop_targets:
  d_drop_target:
    switch: s_drop_target
    reset_coil: c_reset_drop_target
    knockdown_coil: c_knock_down_coil
    #enable_events: machine_reset_phase_3

drop_target_banks:
  noah:
    drop_targets: d_drop_target
    reset_events: 
        machine_reset_phase_3: 0 
        ball_started.1: 0
        ball_started.2: 1s
        ball_started.3: 2s
    reset_on_complete: 1s


lights:
  l_led0:
    number: 8-0-1-2

ball_devices:
  bd_trough:
    ball_switches: s_trough1
    eject_coil: c_trough_eject
    tags: trough, home, drain
    #eject_targets: bd_plunger
    #jam_switch: s_trough_jam
    #eject_coil_jam_pulse: 15ms
    debug: true

#eject_targets: bd_plunger

keyboard:
    z: 
        switch: s_left_flipper
    '/':
        switch: s_right_flipper
    a:
        switch: s_left_slingshot
    ';':
        switch: s_right_slingshot
    's':
        switch: s_start
    'q':
        switch: s_right_inlane
        
        
displays:
    window:
        width: 800
        height: 600


slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        font_size: 90
        color: yellow

      - type: rectangle
        width: 600
        height: 120
        color: green
        
slide_player:
  init_done: welcome_slide
##! test
#advance_time_and_run .1
        
modes:
  - base
  



