#config_version=5

hardware:
    platform: p3_roc
    driverboards: pdb

switches:
    s_left_slingshot:
        number: A0-B0-0
        tags: left_flipper
    s_right_slignshot:
        number: A0-B0-2
        tags: right_flipper

    s_left_flipper:
        number: A0-B0-1
        tags: left_flipper
    s_right_flipper:
        number: A0-B0-3
        tags: right_flipper

coils:
    c_flipper_left_main:
        number: A0-B0-6
        default_pulse_ms: 5
    c_flipper_left_hold:
        number: A0-B0-4
        allow_enable: true
        
    c_flipper_right_main:
        number: A0-B0-7
        default_pulse_ms: 5
    c_flipper_right_hold:
        number: A0-B0-5
        allow_enable: true
        
    c_slingshot_left_main:
        number: A0-B0-2
    c_slingshot_right_main:
        number: A0-B0-3

playfields:
    playfield:
        tags: default
        default_source_device: None  # use None in steps before 8

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
        enable_events: machine_reset_phase_3

keyboard:
    z: 
        switch: s_left_flipper
    '/':
        switch: s_right_flipper

