#config_version=5
##! show: attract_display_loop
##! mode: attract

show_player:
  mode_attract_started: attract_display_loop
  mode_attract_started.1: 
    attract_light_show:
      speed: 4
        

  
  