#config_version=5

# Noah's test file for driving Andy Cavatorta's: Individual, Money, and Society

hardware:
    platform: p3_roc
    driverboards: pdb

switches:
    s_left_flipper:
        number: A0-B0-0
        tags: left_flipper
    s_right_flipper:
        number: A0-B0-1
        tags: right_flipper

    s_left_slingshot_main:
        number: A0-B0-2
    s_right_slingshot_main:
        number: A0-B0-3

    s_rollover_1:
        number: A0-B0-4
    s_rollover_2:
        number: A0-B0-5
    s_rollover_3:
        number: A0-B0-6
    s_rollover_4:
        number: A0-B0-7

    s_pop_bumper_1:
        number: A0-B1-0
    s_pop_bumper_2:
        number: A0-B1-1
    s_pop_bumper_3:
        number: A0-B1-2

    # Trough
    s_trough1:
        number: A0-B1-7

coils:
    # Flippers
    c_flipper_left_main:
        number: A0-B1-0
        default_pulse_ms: 15
        default_pulse_power: 1.0
        allow_enable: true
    c_flipper_left_hold:
        number: A0-B1-1
        default_hold_power: 1.0
        allow_enable: true
        
    c_flipper_right_main:
        number: A0-B1-2
        default_pulse_ms: 15
        default_pulse_power: 1.0
        allow_enable: true
    c_flipper_right_hold:
        default_hold_power: 1.0
        number: A0-B1-3
        allow_enable: true

    c_trough_eject:
        # actually just a placeholder for now!
        number: A0-B0-7

    # Slingshots
    c_slingshot_left_main:
        number: A0-B1-4
        default_pulse_ms: 5
    c_slingshot_right_main:
        number: A0-B1-5
        default_pulse_ms: 5
    
    # Pop Bumpers
    c_pop_bumper_1:
        number: A0-B0-2
    c_pop_bumper_2:
        number: A0-B0-3
    c_pop_bumper_3:
        number: A0-B0-4
                
playfields:
    playfield:
        default_source_device: bd_trough  # use None in steps before 8
        tags: default

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
        enable_events: machine_reset_phase_3

autofire_coils:
    left_slingshot:
        coil: c_slingshot_right_main
        switch: s_left_slingshot_main
        enable_events: machine_reset_phase_3
    right_slingshot:
        coil: c_slingshot_left_main
        switch: s_right_slingshot_main
        enable_events: machine_reset_phase_3

    left_slingshot_mid:
        coil: c_slingshot_right_mid
        switch: s_left_slingshot_mid
        enable_events: machine_reset_phase_3
    right_slingshot_mid:
        coil: c_slingshot_left_mid
        switch: s_right_slingshot_mid
        enable_events: machine_reset_phase_3

    pop_bumper_1:
        coil: c_pop_bumper_1
        switch: s_pop_bumper_1
        enable_events: machine_reset_phase_3
    pop_bumper_2:
        coil: c_pop_bumper_2
        switch: s_pop_bumper_2
        enable_events: machine_reset_phase_3
    pop_bumper_3:
        coil: c_pop_bumper_3
        switch: s_pop_bumper_3
        enable_events: machine_reset_phase_3


lights:
  l_led0:
    number: 8-0-1-2

ball_devices:
  bd_trough:
    ball_switches: s_trough1
    eject_coil: c_trough_eject
    tags: trough, home, drain
    debug: true

keyboard:
    z: 
        switch: s_left_flipper
    '/':
        switch: s_right_flipper
    a:
        switch: s_left_slingshot
    ';':
        switch: s_right_slingshot
    's':
        switch: s_start
    'q':
        switch: s_right_inlane
        
        
displays:
    window:
        width: 800
        height: 600


slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        font_size: 90
        color: yellow

      - type: rectangle
        width: 600
        height: 120
        color: green
        
slide_player:
  init_done: welcome_slide
##! test
#advance_time_and_run .1
        
modes:
  - base
  



